alias curl.cc="curl cip.cc"
#alias icat="kitty +kitten icat"
alias fcat="img2sixel"
alias ue='rm -rf ~/.idm/uex/*.*|rm -rf ~/.idm/uex/.dat |/usr/local/bin/uex &'
alias aria2='aria2c --conf-path=/etc/aria2/aria2.conf -D'
# alias ns="nnn -de"
alias n="ns -c"
alias en="trans :en -p"
alias zh="trans :zh -p"
alias clearr="gio trash --empty"
alias m="ncmpcpp"

alias in='sudo pacman -S' # install package
alias un='sudo pacman -Rns' # uninstall package
alias up='sudo pacman -Syu' # update system/package/aur
alias pl='pacman -Qs' # list installed package
alias pa='pacman -Ss' # list availabe package
alias pc='sudo pacman -S' # remove unused cache
alias po='pacman -Qtdq | sudo pacman -Rns -' # remove unused packages, also try > pacman -Qqd | pacman -Rsu 
alias sl='sway-launcher-desktop'
alias xy='watch -n 0.1 xdotool getmouselocation' #获取鼠标坐标
alias ys='hyprpicker'
alias e='emacs -nw'
alias v2='sudo systemctl start v2raya.service'
#alias ect='emacsclient -t -a ""'
#alias ec='emacsclient -c'
#alias e='emacs'
#alias t='terminology'
#alias ne='neofetch | lolcat'
alias fet='fastfetch | lolcat'
alias themes='kitty +kittyen themes'
#alias bg='swww init && /home/arch/.config/swww/swww_randomize.sh'
#alias wb='waybar --config /home/arch/.config/waybar/hyprland/config'
#alias ld='xbacklight' #-get
#alias yl='alsamixer'
alias hy='Hyprland'
alias tl='tldr'
alias re='trash -put'
#alias uppackge='~/.config/conky/updates.sh'
alias kk='kitty +kitten'
